pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    // Force Git to use the cmd version on Windows
                    bat 'git clone https://github.com/Palak4796/SIT313Task8.1D.git'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    bat 'npm install'
                }
            }
        }

        stage('Build React App') {
            steps {
                script {
                    bat 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo "Build completed successfully!"
        }
        failure {
            echo "Build failed!"
        }
    }
}
